"$schema" = "https://starship.rs/config-schema.json"

# Available palettes:
# - monochrome
palette = "monochrome"

format = "\\[$directory$git_branch$git_status\\] $character"
add_newline = false

[directory]
truncation_symbol = " "
truncation_length = 2
truncate_to_repo = true
style = "fg:frost"
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "fg:spark"
format = " | [[$symbol $branch](fg:spark)]($style)"

[git_status]
format = "$all_status$ahead_behind"
conflicted = " | [ $count](fg:nova)"
ahead = " | [ $count](fg:nova)"
behind = " | [ $count](fg:nova)"
diverged = " | [ $ahead_count  $behind_count](fg:nova)"
untracked = " | [󰞋 $count](fg:nova)"
stashed = " | [󰒲 $count](fg:nova)"
modified = " | [󰏫 $count](fg:nova)"
staged = " | [󰱒 $count](fg:nova)"
renamed = " | [󰁕 $count](fg:nova)"
deleted = " | [󰍵 $count](fg:nova)"

[character]
disabled = false
success_symbol = "[\\$](fg:lime)"
error_symbol = "[\\$](fg:ember)"
vimcmd_symbol = "[\\$](fg:lime)"
vimcmd_replace_one_symbol = "[\\$](fg:iris)"
vimcmd_replace_symbol = "[\\$](fg:iris)"
vimcmd_visual_symbol = "[\\$](fg:spark)"

[palettes.monochrome]
# Accent Colors
lychee  = "#f5f5f5"
guava   = "#eaeaea"
fizz    = "#e0e0e0"
nebula  = "#d6d6d6"
ember   = "#cccccc"
cinder  = "#c2c2c2"
torch   = "#b8b8b8"
spark   = "#aeaeae"
lime    = "#a4a4a4"
surge   = "#9a9a9a"
pulse   = "#909090"
frost   = "#868686"
nova    = "#7c7c7c"
iris    = "#727272"

# Base Colors
text    = "#ffffff"
sub1    = "#f0f0f0"
sub0    = "#dcdcdc"
ov2     = "#c8c8c8"
ov1     = "#b4b4b4"
ov0     = "#a0a0a0"
surf2   = "#8c8c8c"
surf1   = "#787878"
surf0   = "#646464"
base    = "#1c1c1c"
mantle  = "#121212"
crust   = "#080808"
